### ISSUE TITLE
Scheme player shows white bar on top

### ISSUE THREAD

**Issue by almereyda** [ishubin/schemio#608]
When exporting a Scheme to HTML and hopening it through a local webserver (`file://` URLs actually won't work), the player is displayed and the graph is interactive, but a white bar is shown atop.

![Bildschirmfoto von 2022-08-07 17-25-58](https://user-images.githubusercontent.com/1645308/183298458-064a6f4b-caf7-4285-bdab-bc8a93bfdfa7.png)

I am not sure if this is a design decision, or accidental.

https://github.com/ishubin/schemio/blob/5affdc532a069647dae7784a1c732500e13c235e/assets/schemio-standalone.html#L10

Could this eventually be removed, in order to save some screen estate?

![Bildschirmfoto von 2022-08-07 17-28-45](https://user-images.githubusercontent.com/1645308/183298539-4200bba7-4e10-4294-962a-84c1159a159b.png)

**Comment by ishubin** [comment]
Have no idea why that margin is there in a first place. Probably a leftover of some CSS experiments that went unnoticed. I haven't polished standalone player yet.

**Comment by ishubin** [comment]
yeah, I quickly tested it and I don't really see any uses for this top margin. I will remove it and release an update

**Comment by almereyda** [comment]
Many thanks! Beautiful.
