### ISSUE TITLE
Offline Editor : read Schemio JSON from URL

### ISSUE THREAD

**Issue by almereyda** [ishubin/schemio#609]
We can always pass custom values, like a JSON string, into a URL, e.g. after a `#`.

Then this JSON can be loaded and displayed.

URL storage can also be an alternative to localStorage, and allows to distribute interactive Schemio graphs easily "offline", where no HTML export is available.

Additionally, one can also imagine to pass a URL to a scheme's JSON file, and try to retrieve it with CORS, if available.

**Comment by ishubin** [comment]
Interesting idea, I really like it! Do you know if there are limitations for the size of URL fragment in different browsers? I know that there are limitations to URL length but I know nothing about the hash. Diagrams in Schemio can be quite heavy. For instance the project I work currently is about 10% done and the JSON document is 40KB in size. That could look ugly once I finish that document and try it into a long URL and share it in some messengers. I always have issues when I need to share some long URL in Slack (I think it breaks parsing of URL that have base64 encoded text in URL fragments).

Should we maybe zip it and base64 encode? I tried it and that 40KB document went to 7.3KB, so that's promising already.

**Comment by almereyda** [comment]
Yes, I think these are two ideas above:

1. One is to just pass a URL to download a JSON file, eventually via CORS.
2. Pass the whole JSON of a scheme can indeed be difficult. I like the idea of a base64 encoded ZIP, though. There's a nice StackOverflow answer about theoretical and practical length of URLs. According to this, major browsers (Firefox, Chromium, Safari) support 32k-64k characters in a URL, despite it it comes with drawbacks in SEO and CDN land.

Actually I didn't think a scheme could grow so large ^_^. So maybe it's a good alternative to have those files referenced from remote locations, instead of adding everything to the URL itself. Sorry for the confusion of two ideas in one place.

**Comment by ivanshubin-tomtom** [comment]
yeah, the document I work on currently in Schemio has frame animations + a lot of event handlers in different items and that can pretty quickly blow up the document size.
I will try to go with zip + base64 as I am already using JSZip library.

**Comment by ishubin** [comment]
yeah, the document I work on currently in Schemio has frame animations + a lot of event handlers in different items and that can pretty quickly blow up the document size.
I will try to go with zip + base64 as I am already using JSZip library.

**Comment by ishubin** [comment]
@almereyda I have implemented exporting diagrams as link and I used an offline-editor for it.
Check it https://schemio.app/#/offline-editor/?doc=UEsDBAoAAAAIALaWCVWccmxXpgEAAAUDAAAIAAAAZG9jLmpzb26VkW9r2zAQxr.Kd3uzgrrZXtO1ohS67A9jeTHSMgajFNk.WyKy5Mpykjb4u_ckZywUNigGS3e.e3z3_HbgRdMD_33LQHlsw3UHvRQd_nC2o3AHpXUG3VJUaqA4T0c2FQAHh6UHBuXgeuso7qwyHh2lhEMRmrfAT_OUwUPozBhsgGfvKZbAZzkpGdEGoaUdTIVVspwEtTKr_VQet_5aWx9HKWz1EM6QpK6L7nKuVblKWrx4113CSIIFSrFWYZod4BqNn1ZSFdX_vLvaLubd92_0i_iNcmUQwCqMXHplzUF59fXXlWuEvw_lGtup4XXqF9W93TzOKd2ilzbU9tJu4tpNHFQY1QpPsty7Adk.JvlPg4sn8PRtTts5YXo1JQBFj8d2CAYo81GUq8YFW4DXQvc4jrf0sANgWNdk1x96YYrPqWu_LJyUMLLnGGul9YRTR1auKcSb_OQDS_Is3b.yo.jhM7wHLGfnJ5FldpZGlnl2Fllm6ewA5ksh3khBpUltXeIlJsXQvEr4UUTKoLbGX6tHEs7O_wk4GLNWvSo07u36v1F_GZKnT1BLAQIUAAoAAAAIALaWCVWccmxXpgEAAAUDAAAIAAAAAAAAAAAAAAAAAAAAAABkb2MuanNvblBLBQYAAAAAAQABADYAAADMAQAAAAA-&m=view

Please let me know if that's what you meant.

**Comment by almereyda** [comment]
Wow, this is beautiful.

Should I add a follow up issue for loading a Schemio JSON from a remote URL?

**Comment by ishubin** [comment]
To be honest I am not sure that fetching remote JSON is going to be practical. I cannot imagine why users would go to such lengths as to store their JSON somewhere and then using the player on schemio.app with a reference to their remote JSON docs. I mean it is not as simple as generating a link with encoded JSON doc. The flow with remote JSON is a bit complicated:
1. User has to export scheme as JSON
2. Manually upload it somewhere
3. Copy the URL
4. Generate a link with a reference to that scheme URL

 Do you think this would be a common use-case? Or am I missing something?

**Comment by almereyda** [comment]
Yes, this procedure is a little cumbersome, but allows non-users of Schemio to display arbitrary Schemes they find or place online without the limitations of the URL encoding.

Yet I believe, as we would be talking about read-only access to these files, this makes more sense in the player instead.
