### ISSUE TITLE
Executing docker run from README doesn't allow creating diagrams

### ISSUE THREAD

**Issue by LoveIsGrief** [ishubin/schemio#647]
In order to test schemio, following the instruction in the README leads to the creation of a docker volume that's only writable by `root`. The user in the docker container however doesn't have write access.

# Suggestion

```bash
mkdir schemio
sudo chown 1001 schemio
docker run -v "$(pwd)/schemio:/opt/schemio" \
    -p 4010:4010 \
    -e FS_ROOT_PATH=/opt/schemio \
    -e SERVER_PORT=4010 \
    binshu/schemio:latest
```

Most linux systems have a user with the ID 1000, maybe it would advisable to create a user in the image with that ID. An alternative might also be to have an docker entry that's started as root, but the creates a user with the ID of the owner of `/opt/schemio` and starts the server with that user.

**Comment by ishubin** [comment]
Thanks for reporting!

How about changing the readme to this?
```
docker run -v "$(pwd):/opt/schemio:rw" \
    -p 4010:4010 \
    -e FS_ROOT_PATH=/opt/schemio \
    -e SERVER_PORT=4010 \
    binshu/schemio:latest
```

From what I understood in the docker docs adding `:rw` to the volume argument should make it writable. I will try it

**Comment by ishubin** [comment]
Fixed and released
