### ISSUE TITLE
Cannot export HTML from github page

### ISSUE THREAD

**Issue by LoveIsGrief** [ishubin/schemio#648]
Why trying to export https://ishubin.github.io/sre-knowledge-base/#/docs/what-happens-when it fails.

These are the errors in the console
![image](https://user-images.githubusercontent.com/2829538/197344101-22cc5d08-6834-4eff-9160-6743968670de.png)

# Browser 

Firefox 105.0.1 (64-bit)

**Comment by ishubin** [comment]
Thanks for reporting. I totally missed this part. It is because it incorrectly references the `assets` path. By default it uses `/assets`, but in case of GitHub pages it needs to be relative. I will fix it

**Comment by ishubin** [comment]
I have pushed a fix to both schemio code and the demo on GitHub pages. It should work now. The only problem that I didn't address yet, it does not export all the referenced media files. But that was always a limitation of the static exporter.

I will release it later once I fix the other issues

**Comment by ishubin** [comment]
Fixed and released
