### ISSUE TITLE
I logged in with GitHub and somehow ended up on someone else's profile

### ISSUE THREAD

**Issue by stefanvaduva** [ishubin/schemio#711]
I’m not sure what else to say! :) I just used the “Sign Up” button on the front page, clicked on the “GitHub” option, and entered my username and password 
![Screenshot 2024-12-17 at 17 09 55](https://github.com/user-attachments/assets/17a09f2c-c79e-439b-86c1-9b57c24f38e0)

**Comment by ishubin** [comment]
Wow, that's not good. Thanks for reporting it!

**Comment by ishubin** [comment]
Found a bug in the backend code. Apparently there was no check for the email when registering users with Github and for some reason for your user and for that other one (then one it logged you in with) Github does return the user email. I have released a temporary fix that should at least block access for such accounts. Could you please try again? I guess now it just should not let you login with your GitHub user. The next step would be to figure out why exactly it does not share the email with the app.

**Comment by stefanvaduva** [comment]
Indeed, now it just says "There was a problem authenticating with your GitHub account".

**Comment by stefanvaduva** [comment]
The issue might be related to the type of permissions your app is requesting. It looks like you're requesting "Access public information (read-only)", but shouldn’t it be "Access user email addresses (read-only)" instead? Just a guess, but maybe it only works for users who have their email set as public on GitHub

**Comment by ishubin** [comment]
I have released a complete fix. Now it should work even if your email is hidden. I have followed your suggestion and added a `user:email` scope so that it requests it from the user and is able to request the email. Also fixed the api calls on the server and now it requests the user email addresses from GitHub properly. Thank you very much for reporting it!

**Comment by stefanvaduva** [comment]
Cool, it works now, even though my email isn’t public. However, just a heads-up: I now have two profiles on Schem.io. It might be worth checking this so that you ensure users don’t end up with duplicate profiles or get confused if they can’t find their old diagrams because the platform created a new profile. But I guess the initial issue was fixed, so this can be closed. 

Schemio is amzing, congratulation!
