### ISSUE TITLE
Add Tables cell identifier to Schemio script in documentation

### ISSUE THREAD

**Issue by mrtnRivera** [ishubin/schemio#720]
Please add the proper syntax to the setText() function when writing values to the Table shapes cells on the documentation. 
Took me a while to find out that ` setText('c_0_0','MyText')` is the correct way of adding text to the first cell.
Found it on a commit for Tables implamentation:

![image](https://github.com/user-attachments/assets/55a2b64a-53fb-4bf3-b694-d4395cf7f40d)

Furthermore, thank you for this awesome project. Been using Schemio recently and im excited to explore its posibilities.

**Comment by ishubin** [comment]
That's a good idea! I think I could add a special function for the `table` shape. It would work something like this:

```
table = @Table
table.setCellText(0, 0, 'Text')
```
And a similar function for getting text:
```
text = table.getCellText(0, 0)
```
What do you think?

**Comment by ishubin** [comment]
I prepared a quick MR https://github.com/ishubin/schemio/pull/721/files
I can't think at this moment of any other useful script functions for `table` shape so I only came up with the two I mentioned in previous comment

**Comment by mrtnRivera** [comment]
That is very cool! 
I think is very usefull, since the Table shape seem like an excellent place to store and retrieve results from scripts computations.
Again thanks for this awesome project! Happy new year!

**Comment by ishubin** [comment]
Merged and released. The two functions `setCellText` and `getCellText` should be available from SchemioScript now
